"""create folder, photo

Revision ID: 0.0.1
Revises: 
Create Date: 2023-04-16 23:28:54.434863

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "0.0.1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folder",
        sa.Column(
            "uuid",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
            comment="폴더 UUID, Front 제공용 ID",
        ),
        sa.Column("name", sa.String(length=50), nullable=False, comment="폴더 이름"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
        comment="사진첩 폴더",
    )
    op.create_table(
        "photo",
        sa.Column(
            "uuid",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
            comment="사진 UUID, Front 제공용 ID",
        ),
        sa.Column("memo", sa.String(length=1000), nullable=True, comment="사진 메모"),
        sa.Column("url", sa.String(length=500), nullable=False, comment="사진 URL"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "folder_uuid",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
            comment="폴더 UUID",
        ),
        sa.ForeignKeyConstraint(
            ["folder_uuid"],
            ["folder.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
        comment="포토북, 사진 데이터",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photo")
    op.drop_table("folder")
    # ### end Alembic commands ###
