"""create folder, photo

Revision ID: 0.0.1
Revises: 
Create Date: 2023-05-05 16:05:03.376304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0.0.1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    folder = op.create_table(
        "folder",
        sa.Column(
            "uuid",
            sa.String(length=36),
            nullable=False,
            comment="폴더 UUID, Front 제공용 ID",
        ),
        sa.Column(
            "name",
            sa.String(length=20),
            nullable=False,
            comment="폴더 이름",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=6),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 일자",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=6),
            server_default=sa.text("now()"),
            nullable=False,
            comment="수정 일자",
        ),
        sa.Column(
            "deleted_at",
            sa.TIMESTAMP(timezone=6),
            nullable=True,
            comment="삭제 일자",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
        comment="사진첩 폴더",
    )
    op.create_table(
        "photo",
        sa.Column(
            "uuid",
            sa.String(length=36),
            nullable=False,
            comment="사진 UUID, Front 제공용 ID",
        ),
        sa.Column(
            "memo",
            sa.String(length=1000),
            nullable=True,
            comment="사진 메모",
        ),
        sa.Column(
            "url",
            sa.String(length=400),
            nullable=False,
            comment="사진 URL",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=6),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 일자",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=6),
            server_default=sa.text("now()"),
            nullable=False,
            comment="수정 일자",
        ),
        sa.Column(
            "deleted_at",
            sa.TIMESTAMP(timezone=6),
            nullable=True,
            comment="삭제 일자",
        ),
        sa.Column(
            "folder_uuid",
            sa.String(length=255),
            nullable=True,
            comment="폴더 UUID",
        ),
        sa.ForeignKeyConstraint(
            ["folder_uuid"],
            ["folder.uuid"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
        comment="포토북, 사진 데이터",
    )
    # ### end Alembic commands ###
    base_path = "migrations/data/"
    file_path = f"{base_path}folder.json"
    with open(file_path) as fp:
        data = fp.read()
        op.bulk_insert(folder, data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photo")
    op.drop_table("folder")
    # ### end Alembic commands ###
